/**
 * Knowledge Registry
 * Generated by sync_knowledge.ps1
 * DO NOT EDIT MANUALLY
 */

export interface SynergyItem {
    target: string;
    label: string;
    description: string;
    boost: number;
}

export interface KnowledgePack {
    id: string;
    title: string;
    type: string;
    status: string;
    confidence: number;
    tags: string[];
    approvedClaims: string[];
    forbiddenTerms: string[];
    disclaimers: string[];
    synergies: SynergyItem[];
}

export const KNOWLEDGE_REGISTRY: Record<string, KnowledgePack> = {
    "EWOT": {
        id: "KP-EWOT-001",
        title: "EWOT Safety & Education-Only Claims",
        type: "Knowledge Pack",
        status: "Verified",
        confidence: 0.88,
        tags: ["EWOT", "Oxygen", "Exercise", "Compliance", "Safety"],
        approvedClaims: [
            "May support aerobic capacity and endurance",
            "Designed to enhance tissue oxygenation during exercise",
            "May support post-workout recovery",
            "Designed to improve oxygen delivery to peripheral tissues",
            "May support cognitive clarity post-session",
            "Designed to aid microcirculatory function",
            "May support mitochondrial efficiency through oxygen loading",
            "Designed for use alongside low-to-moderate aerobic exercise"
        ],
        forbiddenTerms: ["cure", "treat", "diagnose", "heal", "prevents disease", "medical treatment"],
        disclaimers: [
            "EWOT is designed to support wellness goals and educational planning. Consult a qualified healthcare professional before beginning an exercise-based oxygen routine, particularly if you have cardiovascular or respiratory conditions."
        ],
        synergies: [
            { target: "HBOT", label: "Oxygen Amplifier", description: "EWOT primes circulatory pathways for enhanced HBOT delivery", boost: 40 },
            { target: "HYDROGEN", label: "Oxidative Balance", description: "H2 neutralizes exercise-induced free radicals post-EWOT", boost: 30 }
        ]
    },
    "SAUNA_BLANKET": {
        id: "KP-SAUNA-001",
        title: "Sauna Blanket Safety & Education-Only Claims",
        type: "Knowledge Pack",
        status: "Verified",
        confidence: 0.87,
        tags: ["Sauna", "Infrared", "Heat", "Recovery", "Compliance", "Safety"],
        approvedClaims: [
            "May support deep muscle relaxation",
            "Designed to promote circulatory warmth and vasodilation",
            "May assist with metabolic clearance through perspiration",
            "Designed to support skin vitality through thermal stimulation",
            "May support parasympathetic tone and wind-down",
            "Designed to promote heat shock protein expression",
            "May aid post-exercise recovery and soreness reduction",
            "Designed to support cardiovascular conditioning through passive heat"
        ],
        forbiddenTerms: ["cure", "treat", "diagnose", "detoxify completely", "eliminates toxins", "prevents disease"],
        disclaimers: [
            "The Sauna Blanket is designed to support wellness and recovery goals for general wellbeing. Adequate hydration is essential before and after use. Consult a qualified healthcare professional before use if you have cardiovascular concerns, are pregnant, or have a chronic health condition."
        ],
        synergies: [
            { target: "RLT", label: "Collagen & Heat Stack", description: "Heat primes tissue for deeper photobiomodulation penetration", boost: 30 },
            { target: "EMS", label: "Recovery Accelerator", description: "Infrared heat flushes metabolic waste post-EMS activation", boost: 25 }
        ]
    },
    "EMS": {
        id: "KP-EMS-001",
        title: "EMS Safety & Education-Only Claims",
        type: "Knowledge Pack",
        status: "Verified",
        confidence: 0.89,
        tags: ["EMS", "Muscle", "Stimulation", "Recovery", "Compliance", "Safety"],
        approvedClaims: [
            "Designed to activate a broad spectrum of muscle fiber types simultaneously",
            "May support muscle strength and endurance development",
            "Designed to enhance neuromuscular recruitment efficiency",
            "May support post-exercise recovery acceleration",
            "Designed to assist with metabolic rate optimization",
            "May support rehabilitation and muscle maintenance protocols",
            "Designed for time-efficient full-body conditioning",
            "May assist with deep stabilizer muscle activation"
        ],
        forbiddenTerms: ["cure", "treat", "diagnose", "replaces surgery", "prevents disease", "weight loss guarantee"],
        disclaimers: [
            "EMS is designed to support fitness and wellness goals for general wellbeing. EMS is contraindicated for individuals with pacemakers, implanted defibrillators, or during pregnancy. Always begin at low intensity and consult a qualified healthcare professional before use."
        ],
        synergies: [
            { target: "SAUNA_BLANKET", label: "Activation & Recovery", description: "Infrared heat flushes metabolic waste after EMS-induced muscle fatigue", boost: 25 },
            { target: "PEMF", label: "Cellular Repair Stack", description: "PEMF restores cellular charge after EMS-induced muscle stress", boost: 35 }
        ]
    },
    "VNS": {
        id: "KP-VNS-001",
        title: "VNS Safety & Education-Only Claims",
        type: "Knowledge Pack",
        status: "Verified",
        confidence: 0.91,
        tags: ["VNS", "Vagus", "Nerve", "Stress", "Compliance", "Safety"],
        approvedClaims: [
            "Designed to support parasympathetic nervous system activation",
            "May support heart rate variability (HRV) normalization",
            "Designed to promote stress resilience and recovery",
            "May assist with sleep onset and sleep architecture",
            "Designed to support anti-inflammatory autonomic pathways",
            "May support mood and cognitive baseline",
            "Designed to deliver non-invasive auricular vagal stimulation",
            "May support autonomic nervous system flexibility"
        ],
        forbiddenTerms: ["cure", "treat", "diagnose", "replaces medication", "prevents seizures", "prevents disease"],
        disclaimers: [
            "The VNS Device is designed to support nervous system wellness for general wellbeing. It is contraindicated for individuals with pacemakers, implanted VNS devices, or carotid artery disease. Consult a qualified healthcare professional before use, especially if you take cardiac or neurological medication."
        ],
        synergies: [
            { target: "PEMF", label: "Nervous System Reset", description: "PEMF and VNS create comprehensive autonomic recalibration together", boost: 45 },
            { target: "HYDROGEN", label: "Neurological Protection", description: "H2 neutralizes CNS oxidative load while VNS reduces neuroinflammation", boost: 30 }
        ]
    },
    "HYPOXIC": {
        id: "KP-HYPOXIC-001",
        title: "Hypoxic Generator Safety & Education-Only Claims",
        type: "Knowledge Pack",
        status: "Verified",
        confidence: 0.86,
        tags: ["Hypoxic", "Altitude", "Training", "Performance", "Compliance", "Safety"],
        approvedClaims: [
            "Designed to simulate altitude training conditions",
            "May support EPO production and red blood cell adaptation",
            "Designed to promote mitochondrial density through hypoxic signaling",
            "May support VO2 Max improvement through structured altitude protocols",
            "Designed to activate HIF-1α adaptive pathways",
            "May support cardiovascular efficiency in trained individuals",
            "Designed for use with structured intermittent hypoxic exposure protocols",
            "May support aerobic endurance development"
        ],
        forbiddenTerms: ["cure", "treat", "diagnose", "safe for everyone", "prevents disease", "guaranteed results"],
        disclaimers: [
            "The Hypoxic Generator is designed for athletic performance and wellness optimization. It is contraindicated during pregnancy and for individuals with severe respiratory or cardiovascular conditions. SpO2 monitoring is required during sessions, and a qualified healthcare professional should be consulted before beginning altitude simulation training."
        ],
        synergies: [
            { target: "HBOT", label: "Altitude-Oxygen Paradox", description: "Contrast hypoxic training with HBOT recovery for maximum HIF-1α adaptation", boost: 55 },
            { target: "EWOT", label: "Hyperoxic Rebound", description: "Follow hypoxic sessions with EWOT for the ultimate oxygen contrast protocol", boost: 45 }
        ]
    },
    "CRYO": {
        id: "KP-CRYO-001",
        title: "Cryo Chamber Safety & Education-Only Claims",
        type: "Knowledge Pack",
        status: "Verified",
        confidence: 0.90,
        tags: ["Cryo", "Cryotherapy", "Recovery", "Inflammation", "Compliance", "Safety"],
        approvedClaims: [
            "May support rapid post-exercise recovery",
            "Designed to promote inflammatory response modulation",
            "May support pain relief through cold-induced analgesic mechanisms",
            "Designed to trigger beneficial norepinephrine release",
            "May support mood and energy levels through sympathetic activation",
            "Designed to assist with reactive hyperemia and circulatory flush",
            "May support cold-shock protein expression for cellular resilience",
            "Designed for 2-3 minute whole-body cold exposure protocols"
        ],
        forbiddenTerms: ["cure", "treat", "diagnose", "prevents injury", "cures inflammation", "prevents disease"],
        disclaimers: [
            "The Cryo Chamber is designed to support recovery and wellness goals for general wellbeing. It is contraindicated for individuals with Raynaud's disease, cold urticaria, cryoglobulinemia, cardiovascular conditions, during pregnancy, or with open wounds. Consult a qualified healthcare professional before use."
        ],
        synergies: [
            { target: "SAUNA_BLANKET", label: "Hot-Cold Contrast", description: "Alternating cryo and infrared creates powerful cardiovascular conditioning", boost: 50 },
            { target: "PEMF", label: "Recovery Stack", description: "PEMF restores cellular charge after cryo-induced vasoconstriction", boost: 35 }
        ]
    },
    "HBOT": {
        id: "KP-HBOT-001",
        title: "HBOT Safety & Education-Only Claims",
        type: "Knowledge Pack",
        status: "Verified",
        confidence: 0.95,
        tags: ["HBOT", "Compliance", "Safety", "Legal"],
        approvedClaims: ["Optimizes cellular oxygenation", "Supports mitochondrial efficiency", "Enhances ATP energy production", "Aids in reducing oxidative stress", "Supports post-workout recovery", "Helps flush metabolic waste (lactate)", "Promotes natural regeneration cycles", "Supports cognitive clarity and focus", "Revitalizes energy levels", "Promotes deep relaxation", "Supports healthy circulation"],
        forbiddenTerms: ["Cures Cancer", "Treats Autism / ASD", "Heals Lyme Disease", "Prevents Alzheimer's", "Fixes Long COVID", "Guaranteed healing", "Reverses aging", "Alternative to surgery"],
        disclaimers: ["Hylono technology is designed for wellness and bio-optimization in a general-wellbeing context. Confirm suitability with a qualified healthcare professional before use."],
        synergies: [        {
            target: "PEMF",
            label: "Electromagnetic Priming",
            description: "PEMF before HBOT increases cell membrane permeability, supporting oxygen uptake resonance",
            boost: 15
        },
        {
            target: "RLT",
            label: "Mitochondrial Cascading",
            description: "RLT primes mitochondria for ATP; HBOT provides the necessary oxygen substrate",
            boost: 20
        },
        {
            target: "HYDROGEN",
            label: "Oxidative Balance",
            description: "HBOT increases oxygen availability while Hydrogen neutralizes selective oxidative byproducts",
            boost: 10
        }]
    },
    "HYDROGEN": {
        id: "KP-H2-001",
        title: "Molecular Hydrogen Safety & Claims",
        type: "Knowledge Pack",
        status: "Verified",
        confidence: 0.95,
        tags: ["Hydrogen", "Compliance", "Safety", "Selective Antioxidant"],
        approvedClaims: ["Provides selective antioxidant support against oxidative stress", "Helps maintain physiological redox homeostasis", "Supports cognitive clarity and neurological wellness", "Assists in optimizing metabolic vitality", "Promotes natural recovery from physical exertion"],
        forbiddenTerms: ["Cures Diabetes", "Treats Alzheimer's", "Eliminates systemic inflammation", "Guarantees 20% increase in athletic output", "Reverses cellular damage"],
        disclaimers: ["Hylono technology is designed for wellness and bio-optimization in a general-wellbeing context. Confirm suitability with a qualified healthcare professional before use."],
        synergies: [        {
            target: "HBOT",
            label: "Oxidative Balance",
            description: "Hydrogen provides selective antioxidant protection while HBOT increases reactive oxygen species for therapeutic signaling",
            boost: 10
        },
        {
            target: "PEMF",
            label: "Detox Resonance",
            description: "PEMF session before Hydrogen maximizes systemic distribution through enhanced microcirculation",
            boost: 10
        },
        {
            target: "RLT",
            label: "Photodynamic Synergy",
            description: "Hydrogen supports mitochondrial resilience during high-intensity light exposure",
            boost: 15
        }]
    },
    "PEMF": {
        id: "KP-PEMF-001",
        title: "PEMF Safety & Claims",
        type: "Knowledge Pack",
        status: "Verified",
        confidence: 0.90,
        tags: ["PEMF", "Compliance", "Safety", "Cellular Energy"],
        approvedClaims: ["Supports cellular energy optimization", "Encourages healthy microcirculation", "Helps manage daily stress through electromagnetic support", "Uses Earth-mimicking Schumann resonance for relaxation", "Supports natural recovery and regeneration"],
        forbiddenTerms: ["Cures chronic pain", "Heals broken bones", "Treats fibromyalgia", "Alternative to physical therapy", "Instant relief from inflammation"],
        disclaimers: ["Hylono technology is designed for wellness and bio-optimization in a general-wellbeing context. Confirm suitability with a qualified healthcare professional before use."],
        synergies: [        {
            target: "HBOT",
            label: "Electromagnetic Priming",
            description: "PEMF session before HBOT improves membrane potential, facilitating oxygen uptake",
            boost: 15
        },
        {
            target: "HYDROGEN",
            label: "Detox Resonance",
            description: "PEMF supports lymphatic flow while Molecular Hydrogen targets selective free radicals",
            boost: 10
        },
        {
            target: "RLT",
            label: "Vascular Optimization",
            description: "Combined use supports peak microcirculation and tissue regeneration",
            boost: 12
        }]
    },
    "RLT": {
        id: "KP-RLT-001",
        title: "Red Light Therapy Safety & Claims",
        type: "Knowledge Pack",
        status: "Verified",
        confidence: 0.90,
        tags: ["RLT", "PBM", "Compliance", "Safety", "Mitochondrial Health"],
        approvedClaims: ["Supports mitochondrial energy production (ATP)", "Promotes a healthy, radiant glow and skin resilience", "Assists in post-exercise recovery and fatigue management", "Helps regulate natural sleep-wake cycles through light exposure", "Enhances cellular vitality and resilience"],
        forbiddenTerms: ["Cures skin cancer", "Treats eczema", "Improves eyesight", "Cures chronic inflammation", "Permanent fat loss"],
        disclaimers: ["Hylono technology is designed for wellness and bio-optimization in a general-wellbeing context. Confirm suitability with a qualified healthcare professional before use."],
        synergies: [        {
            target: "HBOT",
            label: "Mitochondrial Cascading",
            description: "RLT primes mitochondria via cytochrome c oxidase; HBOT provides the oxygen oxygen substrate for maximized ATP results",
            boost: 20
        },
        {
            target: "PEMF",
            label: "Vascular Optimization",
            description: "PEMF supports the circulatory pathways while RLT acts on the cellular target",
            boost: 12
        },
        {
            target: "HYDROGEN",
            label: "Photodynamic Synergy",
            description: "H2 neutralizes selective oxidative stress occasionally associated with intensive light therapy sessions",
            boost: 15
        }]
    }
};
