/**
 * Knowledge Registry
 * Generated by sync_knowledge.ps1
 * DO NOT EDIT MANUALLY
 */

export interface SynergyItem {
    target: string;
    label: string;
    description: string;
    boost: number;
}

export interface KnowledgePack {
    id: string;
    title: string;
    type: string;
    status: string;
    confidence: number;
    tags: string[];
    approvedClaims: string[];
    forbiddenTerms: string[];
    disclaimers: string[];
    synergies: SynergyItem[];
}

export const KNOWLEDGE_REGISTRY: Record<string, KnowledgePack> = {
    "HBOT": {
        id: "KP-HBOT-001",
        title: "HBOT Safety & Education-Only Claims",
        type: "Knowledge Pack",
        status: "Verified",
        confidence: 0.95,
        tags: ["HBOT", "Compliance", "Safety", "Legal"],
        approvedClaims: ["Optimizes cellular oxygenation", "Supports mitochondrial efficiency", "Enhances ATP energy production", "Aids in reducing oxidative stress", "Supports post-workout recovery", "Helps flush metabolic waste (lactate)", "Promotes natural regeneration cycles", "Supports cognitive clarity and focus", "Revitalizes energy levels", "Promotes deep relaxation", "Supports healthy circulation"],
        forbiddenTerms: ["Cures Cancer", "Treats Autism / ASD", "Heals Lyme Disease", "Prevents Alzheimer's", "Fixes Long COVID", "Guaranteed healing", "Reverses aging", "Alternative to surgery"],
        disclaimers: ["Hylono technology is designed for wellness and bio-optimization. It is not intended to diagnose, treat, cure, or prevent any disease."],
        synergies: [        {
            target: "PEMF",
            label: "Electromagnetic Priming",
            description: "PEMF before HBOT increases cell membrane permeability, supporting oxygen uptake resonance",
            boost: 15
        },
        {
            target: "RLT",
            label: "Mitochondrial Cascading",
            description: "RLT primes mitochondria for ATP; HBOT provides the necessary oxygen substrate",
            boost: 20
        },
        {
            target: "HYDROGEN",
            label: "Oxidative Balance",
            description: "HBOT increases oxygen availability while Hydrogen neutralizes selective oxidative byproducts",
            boost: 10
        }]
    },
    "HYDROGEN": {
        id: "KP-H2-001",
        title: "Molecular Hydrogen Safety & Claims",
        type: "Knowledge Pack",
        status: "Verified",
        confidence: 0.95,
        tags: ["Hydrogen", "Compliance", "Safety", "Selective Antioxidant"],
        approvedClaims: ["Provides selective antioxidant support against oxidative stress", "Helps maintain physiological redox homeostasis", "Supports cognitive clarity and neurological wellness", "Assists in optimizing metabolic vitality", "Promotes natural recovery from physical exertion"],
        forbiddenTerms: ["Cures Diabetes", "Treats Alzheimer's", "Eliminates systemic inflammation", "Guarantees 20% increase in athletic output", "Reverses cellular damage"],
        disclaimers: ["Hylono technology is designed for wellness and bio-optimization. It is not intended to diagnose, treat, cure, or prevent any disease."],
        synergies: [        {
            target: "HBOT",
            label: "Oxidative Balance",
            description: "Hydrogen provides selective antioxidant protection while HBOT increases reactive oxygen species for therapeutic signaling",
            boost: 10
        },
        {
            target: "PEMF",
            label: "Detox Resonance",
            description: "PEMF session before Hydrogen maximizes systemic distribution through enhanced microcirculation",
            boost: 10
        },
        {
            target: "RLT",
            label: "Photodynamic Synergy",
            description: "Hydrogen supports mitochondrial resilience during high-intensity light exposure",
            boost: 15
        }]
    },
    "PEMF": {
        id: "KP-PEMF-001",
        title: "PEMF Safety & Claims",
        type: "Knowledge Pack",
        status: "Verified",
        confidence: 0.90,
        tags: ["PEMF", "Compliance", "Safety", "Cellular Energy"],
        approvedClaims: ["Supports cellular energy optimization", "Encourages healthy microcirculation", "Helps manage daily stress through electromagnetic support", "Uses Earth-mimicking Schumann resonance for relaxation", "Supports natural recovery and regeneration"],
        forbiddenTerms: ["Cures chronic pain", "Heals broken bones", "Treats fibromyalgia", "Alternative to physical therapy", "Instant relief from inflammation"],
        disclaimers: ["Hylono technology is designed for wellness and bio-optimization. It is not intended to diagnose, treat, cure, or prevent any disease."],
        synergies: [        {
            target: "HBOT",
            label: "Electromagnetic Priming",
            description: "PEMF session before HBOT improves membrane potential, facilitating oxygen uptake",
            boost: 15
        },
        {
            target: "HYDROGEN",
            label: "Detox Resonance",
            description: "PEMF supports lymphatic flow while Molecular Hydrogen targets selective free radicals",
            boost: 10
        },
        {
            target: "RLT",
            label: "Vascular Optimization",
            description: "Combined use supports peak microcirculation and tissue regeneration",
            boost: 12
        }]
    },
    "RLT": {
        id: "KP-RLT-001",
        title: "Red Light Therapy Safety & Claims",
        type: "Knowledge Pack",
        status: "Verified",
        confidence: 0.90,
        tags: ["RLT", "PBM", "Compliance", "Safety", "Mitochondrial Health"],
        approvedClaims: ["Supports mitochondrial energy production (ATP)", "Promotes a healthy, radiant glow and skin resilience", "Assists in post-exercise recovery and fatigue management", "Helps regulate natural sleep-wake cycles through light exposure", "Enhances cellular vitality and resilience"],
        forbiddenTerms: ["Cures skin cancer", "Treats eczema", "Improves eyesight", "Cures chronic inflammation", "Permanent fat loss"],
        disclaimers: ["Hylono technology is designed for wellness and bio-optimization. It is not intended to diagnose, treat, cure, or prevent any disease."],
        synergies: [        {
            target: "HBOT",
            label: "Mitochondrial Cascading",
            description: "RLT primes mitochondria via cytochrome c oxidase; HBOT provides the oxygen oxygen substrate for maximized ATP results",
            boost: 20
        },
        {
            target: "PEMF",
            label: "Vascular Optimization",
            description: "PEMF supports the circulatory pathways while RLT acts on the cellular target",
            boost: 12
        },
        {
            target: "HYDROGEN",
            label: "Photodynamic Synergy",
            description: "H2 neutralizes selective oxidative stress occasionally associated with intensive light therapy sessions",
            boost: 15
        }]
    }
};
