export const pdpCommerceContent = {
  trackLabels: {
    buy: 'Buy',
    rent: 'Rent',
    buyLower: 'buy',
    rentLower: 'rent',
    purchaseBadge: 'Purchase',
    rentalBadge: 'Rental',
  },
  cta: {
    addToCart: 'Add to Cart',
    tryIt: 'Try It',
    stickyAddToCart: 'Add to cart',
    stickyTryIt: 'Try it',
    mobileBuy: 'Buy',
    mobileRent: 'Rent',
  },
  pricing: {
    financingAriaLabel: 'Open financing options',
    rentalUnavailable: 'Rental available on request',
    minimumPeriodPrefix: 'Minimum period:',
    refundableDepositPrefix: 'Refundable deposit:',
    savingsPrefix: 'You save',
    noHiddenFees: 'No hidden fees.',
    financingTitle: 'Financing options',
    financingCta: 'More about financing',
    orRentPrefix: 'Or rent:',
    compareBuyRent: 'Compare buying vs renting',
  },
  anxietyBuffers: {
    purchase: [
      '5-year warranty + local service',
      'Free usage protocol included',
      'Trade-in program — exchange your old device for a discount',
      'Post-purchase support: onboarding + ongoing assistance',
      'Secure payment options',
    ],
    rental: [
      'No long-term commitment',
      'Service and support included',
      'Delivery, setup, and instruction included',
      'Buy with a discount — 70% of payments credited toward purchase',
      'Easy returns — we arrange pickup',
    ],
  },
  switchTrack: {
    titlePrefix: 'Switch to',
    switchToPrefix: 'Switch to',
    oneTimePurchaseSuffix: 'one-time purchase',
    minimumPrefix: 'minimum',
    orPrefix: 'or',
    drawerCloseAriaLabel: 'Close alternative track drawer',
    closeFinancingAriaLabel: 'Close financing drawer',
  },
} as const;
