export const seoRedirects = [
  { source: '/products', destination: '/store', permanent: true },
  { source: '/products/:tech', destination: '/product/:tech', permanent: true },
  { source: '/shop', destination: '/store', permanent: true },
  { source: '/journal', destination: '/blog', permanent: true },
  { source: '/journal/:slug', destination: '/blog/:slug', permanent: true },
  { source: '/science', destination: '/research', permanent: true },
  { source: '/sign-in', destination: '/login', permanent: true },
  { source: '/signin', destination: '/login', permanent: true },
  { source: '/account/login', destination: '/login', permanent: true },
  { source: '/partner', destination: '/nexus', permanent: true },
  { source: '/partner/dashboard', destination: '/nexus', permanent: true },
  { source: '/partner/nexus', destination: '/nexus/clients', permanent: true },
  { source: '/partner/fleet', destination: '/nexus/fleet', permanent: true },
  { source: '/partner/docs', destination: '/nexus/docs', permanent: true },
  { source: '/partner/studio', destination: '/nexus/studio', permanent: true },
  { source: '/partner/team', destination: '/nexus/team', permanent: true },
  { source: '/partner/academy', destination: '/nexus/academy', permanent: true },
  { source: '/partner/shop', destination: '/nexus/supplies', permanent: true },
  { source: '/nexus/dashboard', destination: '/nexus', permanent: true },
  { source: '/nexus/nexus', destination: '/nexus/clients', permanent: true },
  { source: '/nexus/shop', destination: '/nexus/supplies', permanent: true },
  { source: '/support', destination: '/help', permanent: true },
  { source: '/guarantee', destination: '/returns', permanent: true },
] as const;
