
# Hylono Knowledge Sync Script
# Parses /research/packs/*.md and updates /constants/knowledge.ts

$packsDir = "research/packs"
$registryFile = "constants/knowledge.ts"

Write-Host "Syncing Knowledge Packs..." -ForegroundColor Cyan

$registryItems = @()

Get-ChildItem -Path $packsDir -Filter "*_safety_claims.md" | ForEach-Object {
    $content = Get-Content $_.FullName
    $fileName = $_.Name
    Write-Host "→ Syncing: $fileName" -ForegroundColor Cyan

    $id = ""; $title = ""; $confidence = ""; $tags = ""; $modality = $_.BaseName.Split('_')[0].ToUpper()
    $claims = @(); $forbidden = @(); $synergies = @(); $currentSection = ""

    foreach ($line in $content) {
        if ($line -match "id: (KP-\w+-\d+)") { $id = $matches[1] }
        if ($line -match "title: ""(.+)""") { $title = $matches[1] }
        if ($line -match "confidence_score: (0\.\d+)") { $confidence = $matches[1] }
        if ($line -match "tags: \[(.+)\]") { $tags = $matches[1] }

        if ($line -match "## 2. Approved") { $currentSection = "approved" }
        elseif ($line -match "## 3. Forbidden") { $currentSection = "forbidden" }
        elseif ($line -match "## 7. Synergy") { $currentSection = "synergy" }
        elseif ($line -match "## ") { $currentSection = "" }

        if ($line -match "^\s*-\s+""(.+)""") {
            if ($currentSection -eq "approved") { $claims += $matches[1] }
            elseif ($currentSection -eq "forbidden") { $forbidden += $matches[1] }
        }
        elseif ($currentSection -eq "synergy" -and $line -match "^\s*-\s*\*\*(\w+)\*\*:\s*""([^""]+)""\s*-\s*(.+?)\s*\(\+(\d+)% Synergy\)") {
            $synergyItem = @"
        {
            target: "$($matches[1])",
            label: "$($matches[2])",
            description: "$($matches[3])",
            boost: $($matches[4])
        }
"@
            $synergies += $synergyItem
        }
    }

    if ($id) {
        $claimsString = ($claims | ForEach-Object { "`"$_`"" }) -join ", "
        $forbiddenString = ($forbidden | ForEach-Object { "`"$_`"" }) -join ", "
        $synergyString = $synergies -join ",`n"
        
        $item = @"
    "$modality": {
        id: "$id",
        title: "$title",
        type: "Knowledge Pack",
        status: "Verified",
        confidence: $confidence,
        tags: ["$($tags -replace ', ', '", "')"],
        approvedClaims: [$claimsString],
        forbiddenTerms: [$forbiddenString],
        disclaimers: ["Hylono technology is designed for wellness and bio-optimization. It is not intended to diagnose, treat, cure, or prevent any disease."],
        synergies: [$synergyString]
    }
"@
        $registryItems += $item
    }
}

$newContent = @"
/**
 * Knowledge Registry
 * Generated by sync_knowledge.ps1
 * DO NOT EDIT MANUALLY
 */

export interface SynergyItem {
    target: string;
    label: string;
    description: string;
    boost: number;
}

export interface KnowledgePack {
    id: string;
    title: string;
    type: string;
    status: string;
    confidence: number;
    tags: string[];
    approvedClaims: string[];
    forbiddenTerms: string[];
    disclaimers: string[];
    synergies: SynergyItem[];
}

export const KNOWLEDGE_REGISTRY: Record<string, KnowledgePack> = {
$($registryItems -join ",`n")
};
"@

$newContent | Set-Content $registryFile
Write-Host "Sync Complete: $($registryItems.Count) packs registered." -ForegroundColor Green
